### PR TITLE
Add `graph` instance attribute to `nx.Graph`

### PR DESCRIPTION
**Pull request by jaywonchung**
NetworkX graphs support graph attributes: https://networkx.org/documentation/stable/tutorial.html#graph-attributes

Initialized like this in the constructor of [`nx.Graph`](https://github.com/networkx/networkx/blob/079c04a4b02ba0f0dd1ab1e05ec5bde62490a95b/networkx/classes/graph.py#L365) and [`nx.DiGraph`](https://github.com/networkx/networkx/blob/079c04a4b02ba0f0dd1ab1e05ec5bde62490a95b/networkx/classes/digraph.py#L349).

However, this doesn't exist in the `graph.pyi` or `digraph.pyi` stubs, resulting in a *Cannot access member* error from type checking.

I saw the README comment that these stub files were automatically generated with docs2stubs. Perhaps this should be understood as a limitation of docs2stubs, and the appropriate fix would be to first upstream a fix to docs2stubs and then re-generate the stubs here. I'll leave this decision to the maintainers. I don't have the bandwidth to do that at the moment.

### CODE REVIEW

**Comment by jaywonchung** [comment]
@microsoft-github-policy-service agree

**Review by debonte — APPROVED** [review]

**Comment by debonte** [comment]
Thanks @jaywonchung. I wonder if users will want a type annotation for `graph` at some point (some sort of dictionary?). But if this fixes things on your side, I'm fine with a minimalist change for now.

**Comment by jaywonchung** [comment]
The thing is, NetworkX allows users to subclass `nx.Graph` or `nx.DiGraph` and set the class variable `graph_attr_dict_factory`, which is used to instantiate `self.graph`. NetworkX just requires ([ref](https://networkx.org/documentation/stable/reference/classes/graph.html)):
> `graph_attr_dict_factory` function, (default: dict)
> Factory function to be used to create the graph attribute dict which holds attribute values keyed by attribute name. It should require no arguments and return a dict-like object.

One immediate way I can think of is to make `nx.Graph` a `Generic[GA]` with `GA = TypeVar("GA")` (whether `bound=dict` is appropriate is unclear) and annotate `graph_attr_dict_factory: Callable[[], GA]`, but then we'll have to do it for all `node_dict_factory`, `node_attr_dict_factory`, `adjlist_outer_dict_factory`, `adjlist_inner_dict_factory`, and `edge_attr_dict_factory`, which is.... a hell lot of generics. What do you think?

**Comment by debonte** [comment]
Is it common to set a custom `graph_attr_dict_factory`? Maybe it would be simpler to not support that scenario?

Either way, I don't think it makes sense to do this unless you're personally motivated or more users express a need for this.

**Comment by jaywonchung** [comment]
I can't say much about the common use case of NetworkX, but regardless I agree. Let's not think about it now.

**Pull request merged**
