### PR TITLE
Add type stubs for sympy

### PR DESCRIPTION
**Pull request by rchiodo**
In Pylance we've had numerous [performance issues](https://github.com/microsoft/pylance-release/issues?q=is%3Aissue+is%3Aopen+sympy) with Sympy. These stubs eliminate all of the overhead with analyzing sympy.

The stubs were generated from the 1.12 release of Sympy. If Sympy were to ship, there's another [set](https://github.com/rchiodo/python-type-stubs/tree/rchiodo/sympy_stubs) of these stubs that are closer to the Sympy 1.13dev branch.

### CODE REVIEW

**Comment by rchiodo** [comment]
After this PR is submitted, I'll modify the Pylance build to pull them into our bundled stubs.

**Comment by debonte** [comment]
> After this PR is submitted, I'll modify the Pylance build to pull them into our bundled stubs.

We should automatically pull these over via the "Copy python-type-stubs stubs to pylance" step in `update_other_stubs.yml`

**Comment by rchiodo** [comment]
Tested by installing into the 'typings' folder of a workspace and then tried using sympy.

Without these stubs I get this:

```
2024-03-19 14:20:36.867 [info] [Info  - 2:20:36 PM] (9044) [BG(1)] Long operation: analyzing: file:///c%3A/Users/rchiodo/source/testing/Testing_Pyright_2/test_sympy.py (15891ms)
```

**Comment by debonte** [comment]
I think you mentioned at one point that when Pyright generates stubs, the types are initially commented out? Did you write a script to uncomment them? Should we document how to generate/update these stubs?

**Review by debonte — APPROVED** [review]

**Comment by rchiodo** [comment]
> I think you mentioned at one point that when Pright generates stubs, the types are initially commented out? 
Yes that's true. It leaves them commented out.

> Did you write a script to uncomment them? 
I did. I also wrote a script to remove doc strings.

> Should we document how to generate/update these stubs?
At this point they need to be updated by hand I think. 

I'll add a readme.md to the sympy stubs directory.

**Pull request merged**
